version: 1.0.{build}-{branch}
os: Visual Studio 2017
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
matrix:
  fast_finish: true
skip_tags: true
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
cache:
  - packages -> **\packages.config
nuget:
  project_feed: true
artifacts:
- path: CalculatorApi
  type: WebDeployPackage
before_build:
- nuget restore
- ps: Write-Host "Hey .NET community"
build:
  parallel: true
  project: Demo.DotNetMeetup.sln
  verbosity: minimal
  publish_wap: true
deploy:
- provider: WebDeploy
  server: https://calculator-meetup.scm.azurewebsites.net:443/msdeploy.axd?site=calculator-meetup
  website: calculator-meetup
  username: $calculator-meetup
  password:
    secure: aAQLeJlot/LZfDLbiJilNG+6wXPQrUh3JTwcd6tDBMIx9N7ExlUBNRgpF8PxztfPFWIK0bSlHY4I6D33OlETkg==
  remove_files: true
  app_offline: true
  sync-retry-attempts: 2
  artifact: Calculator.API.zip