version: 1.0.{build}-{branch}
os: Visual Studio 2017
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
matrix:
  fast_finish: true
skip_tags: true
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
cache:
  - packages -> **\packages.config
nuget:
  project_feed: true
before_build:
- nuget restore
build:
  parallel: true
  project: Demo.DotNetMeetup.sln
  verbosity: minimal